#!/usr/bin/perl -w

package kconfig;

use strict;
use warnings;
use Exporter 'import';
use IO::File;
use Data::Dumper;

our $VERSION = '1.00';
our @EXPORT = qw(kconfig_gen kconfig_gen_makefile);

my $CONFIG_INFO = 'PConf_driver_info';

sub kconfig_gen(\%$);
sub kconfig_gen_makefile($$);

#
# kconfig_gen_makefile(make_in, make_out)
#
sub kconfig_gen_makefile($$)
{
	my ($make_in, $make_out) = @_;
	my $make_prefix = <<MAKE_PREFIX_END;
#
# DO NOT EDIT - Generated by PConf
#

MAKE_PREFIX_END
	my $mifd = IO::File->new($make_in, O_RDONLY)
				or die 'Couldn\'t open the specified output file!';
	my $mfd = IO::File->new($make_out, O_WRONLY | O_CREAT | O_TRUNC)
				or die 'Couldn\'t open the specified output file!';

	my @make_contents = <$mifd>;

	print $mfd $make_prefix;
	print $mfd @make_contents;

	close->$mfd;
	close->$mifd;
}

#
# kconfig_gen(%options, $output_file
#
sub kconfig_gen(\%$)
{
	my ($options, $kconfig_file) = @_;
	my $kconfig_prefix = <<KCONFIG_PREFFIX_END;
#
# DO NOT EDIT - Generated by PConf
#

KCONFIG_PREFFIX_END
	$kconfig_prefix .= "menuconfig " . $options->{$CONFIG_INFO}->{'definition'} . "\n";
	$kconfig_prefix .= "\t". $options->{$CONFIG_INFO}->{'type'} . " " .
							"\"" . $options->{$CONFIG_INFO}->{'short'} . "\"\n";
	$kconfig_prefix .= "\t---help---\n\t  " . $options->{$CONFIG_INFO}->{'info'} . "\n\n";
	$kconfig_prefix .= "if " . $options->{$CONFIG_INFO}->{'definition'} . "\n";
	
	my $kfd = IO::File->new($kconfig_file, O_WRONLY | O_CREAT | O_TRUNC)
				or die 'Couldn\'t open the specified output file!';

	my @kconf_data = ();

	foreach my $option (keys(%$options)) {
		next if $option eq $CONFIG_INFO;
		push(@kconf_data, "config " . $options->{$option}->{'definition'} . "\n");
		push(@kconf_data, "\t" . $options->{$option}->{'type'} . " \"" . $options->{$option}->{'short'} . "\"\n");
		push(@kconf_data, "\thelp\n" . "\t  " . $options->{$option}->{'info'} . "\n");
	}

	print $kfd $kconfig_prefix;
	print $kfd @kconf_data;
	print $kfd "endif\n\n";
	
	$kfd->close;
}

"1";
